BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  test_script:
    - python --version
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements_dev.txt
    - python -m flake8 --show-source --exclude examples/area_calculator/area_calculator_pb2.py,examples/area_calculator/area_calculator_pb2_grpc.py
    - python -m pydocstyle pact
    - python -m tox -e test
    # - make examples

linux_arm64_task: 
  env:
    PACT_FFI_PATH: .tox/test/lib/python$VERSION/site-packages/pact/bin
    matrix:
      # - IMAGE: python:3.6 # This works locally, with cirrus run, but fails in CI
      # - IMAGE: python:3.7
      # - IMAGE: python:3.8
      # - IMAGE: python:3.9
      # - IMAGE: python:3.10
      - VERSION: 3.6
      - VERSION: 3.7
      - VERSION: 3.8
      - VERSION: 3.9
      - VERSION: 3.10
  arm_container:
    image: python:$VERSION-slim
  install_script:
    - apt update --yes && apt install --yes gcc make
  << : *BUILD_TEST_TASK_TEMPLATE


macos_arm64_task:
  # only_if: $CIRRUS_CHANGE_TITLE =~ 'ci\(macos\).*'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  env:
    PATH: ${HOME}/.pyenv/shims:${PATH}
    PACT_FFI_PATH: .tox/test/lib/python$VERSION/site-packages/pact/bin
    matrix:
      - VERSION: 3.6
      - VERSION: 3.7
      - VERSION: 3.8
      - VERSION: 3.9
      - VERSION: 3.10
  install_script:
    - brew update    
    - brew install pyenv
    - pyenv install ${VERSION}
    - pyenv global ${VERSION}
    - pyenv rehash
  << : *BUILD_TEST_TASK_TEMPLATE
