version: "3.9"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres -U postgres --command 'SELECT 1'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pact-broker:
    image: pactfoundation/pact-broker:latest-multi
    depends_on:
      - postgres
    ports:
      - "9292:9292"
    environment:
      # Basic auth credentials for the Broker
      PACT_BROKER_ALLOW_PUBLIC_READ: "true"
      PACT_BROKER_BASIC_AUTH_USERNAME: pactbroker
      PACT_BROKER_BASIC_AUTH_PASSWORD: pactbroker
      # Database
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--show-error",
          "--fail",
          "http://pactbroker:pactbroker@localhost:9292/diagnostic/status/heartbeat",
        ]
      interval: 1s
      timeout: 2s
      retries: 5
