name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        os: [ ubuntu-latest, windows-latest, macos-latest ]

        # These versions are no longer supported by Python team, and may
        # eventually be dropped from GitHub Actions.
        include:
          - python-version: '3.6'
            os: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: run alpine in docker
        run: |
          (export PY=${{ matrix.python-version }} && docker build --build-arg PY="$PY" --build-arg TOXPY="$(sed 's/\.//' <<< "$PY")" -t pactfoundation:python${PY} -f docker/Dockerfile .)
          docker run -it --rm -v "$(pwd)":/home pactfoundation:python${{ matrix.python-version }} sh -c "apk add bash && cd /home && tox -e py${PY} && make consumer"