name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        os: [ ubuntu-latest ]


    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: run alpine in docker
        run: |
          (export PY=${{ matrix.python-version }} && docker build --build-arg PY="$PY" --build-arg TOXPY="$(sed 's/\.//' <<< "$PY")" -t pactfoundation:python${PY} -f docker/Dockerfile .)
          docker run --rm -v "$(pwd)":/home pactfoundation:python${{ matrix.python-version }} sh -c "apk add bash && cd /home && tox -e py${PY} && make consumer"